collections:
  art-assets:
    image: true
    output: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  # - scope:
  #     path: ""
  #     type: "authors"
  #   values:
  #     layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_art-assets"
    values:
      layout: "art_post"

# theme: jekyll-theme-midnight
